import { Poppins } from "next/font/google";
import "./globals.scss";
import Footer from "./components/Footer/Footer";

const popins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={popins.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
